import React from 'react'
import {Users, Building, Stethoscope} from "lucide-react";

const Card = ({ children }) => (
        <div className="rounded-2xl shadow-md bg-white">{children}</div>
        );

        const CardContent = ({ children, className }) => (
          <div className={`p-4 ${className}`}>{children}</div>
          );

          const DashButton = ({ children, className, ...props }) => (
            <button
                {...props}
                    className={`px-4 py-2 rounded-xl font-medium transition ${className}`}
                      >
                          {children}
                            </button>
                            );

const UserDashboard = () => {
  return (
          <div className="p-6 bg-gray-50 min-h-screen">
              <header className="flex items-center justify-between mb-6">
              <h1 className="text-2xl font-bold text-gray-900">QueueEase</h1>
              <div className="flex items-center gap-3">
                <Button className="bg-blue-600 text-white rounded-xl">Join a Queue</Button>
                <div className="w-10 h-10 bg-gray-200 rounded-full flex items-center justify-center">
                  <span className="text-gray-600">👤</span>
                </div>
              </div>
              </header>

      {/* Active Queues */}
          <section>
            <h2 className="text-lg font-semibold text-gray-700 mb-3">Active Queues</h2>
            <div className="grid md:grid-cols-2 gap-4">
      {/* Queue Card 1 */}
          <Card className="rounded-2xl shadow-md">
            <CardContent className="p-4">
                  <div className="flex items-center gap-2 mb-2">
                     <Users className="text-blue-600" />
                     <h3 className="font-semibold text-gray-900">Tech Solutions Inc. Support</h3>
                  </div>
                  <p className="text-sm text-gray-600">Your Turn: <span className="text-blue-600 font-medium">Now!</span></p>
                  <p className="text-gray-800 mt-1 font-bold">Your Position: 1</p>
                                                                                                                                                                                                                                                                                              <Button className="mt-3 w-full bg-blue-600 text-white">Go to Agent</Button>
                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                    </Card>

                                                                                                                                                                                                                                                                                                                              {/* Queue Card 2 */}
                                                                                                                                                                                                                                                                                                                                        <Card className="rounded-2xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                    <CardContent className="p-4">
                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                  <Building className="text-blue-600" />
                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-semibold text-gray-900">City Hall Services</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                              Estimated wait: <span className="text-blue-600 font-medium">30 minutes</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-800 mt-1 font-bold">Your Position: 12</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button className="mt-3 w-full bg-blue-100 text-blue-600">View Details</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Upcoming Queues */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold text-gray-700 mb-3">Upcoming Queues</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Card className="rounded-2xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardContent className="p-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Stethoscope className="text-blue-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-gray-900">Dr. Emily Carter's Office</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-gray-600">Scheduled for: Tomorrow, 10:00 AM</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button className="bg-blue-100 text-blue-600">View Details</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Past Queues */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section className="mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-lg font-semibold text-gray-700 mb-3">Past Queues</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Card className="rounded-2xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CardContent className="p-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Users className="text-gray-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-gray-700">Tech Solutions Inc. Support</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-500">Completed on: 2024-01-15</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button className="bg-gray-100 text-gray-600">View</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Card className="rounded-2xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent className="p-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Building className="text-gray-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="font-semibold text-gray-700">City Hall Services</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-gray-500">Completed on: 2024-01-10</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button className="bg-gray-100 text-gray-600">View</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div> );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  

export default UserDashboard